#!/bin/bash

DIR=$(realpath $0 | xargs dirname)
COMMAND=$1
SCRIPTS_DIR="$DIR/commands"
SCRIPT="$SCRIPTS_DIR/$COMMAND"

shift # Shift the arguments so that $@ contains the remaining arguments

if [[ -x "$SCRIPT" ]]; then
  "$SCRIPT" "$@"
else
  echo "Error: '$COMMAND' is not a valid command."
  echo "Available commands:"
  for cmd in "$SCRIPTS_DIR/"*; do
    script_name=$(basename "$cmd")
    echo "  ${script_name%.*}"
  done
  exit 1
fi
