#!/bin/bash

REPO_PATH=$(git rev-parse --show-toplevel)

# Derive the repository name from the provided path

REPO_NAME=$(basename "$REPO_PATH")
BACKUP_DIR="/tmp/repo_backups/$REPO_NAME"

tree "$BACKUP_DIR"
